# Generated by Django 3.2.7 on 2022-04-18 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timescales', '0004_auto_20220307_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('website', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(blank=True, max_length=100, null=True)),
                ('summary', models.TextField()),
                ('characteristics', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(blank=True, max_length=100, null=True)),
                ('organism_type', models.CharField(choices=[('AN', 'Animal'), ('PL', 'Plant'), ('BA', 'Bacteria'), ('FU', 'Fungi')], max_length=3)),
                ('endangered', models.BooleanField(default=False)),
                ('habitat', models.TextField(blank=True, null=True)),
                ('extent', models.CharField(blank=True, max_length=50, null=True)),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timescales.geoperiod')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='life.species')),
            ],
        ),
    ]
