# Generated by Django 3.2.7 on 2022-04-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0002_auto_20220418_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='organism',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
