# Generated by Django 3.2.7 on 2022-02-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('extent_mya', models.IntegerField(default=0)),
                ('duration_moy', models.IntegerField(default=0)),
                ('absolute_number', models.IntegerField(default=0)),
                ('period_order_number', models.IntegerField(default=0)),
                ('summary', models.TextField()),
                ('life', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeoEra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('absolute_number', models.IntegerField(default=0)),
                ('era_order_number', models.IntegerField(default=0)),
                ('summary', models.TextField()),
                ('life', models.TextField(blank=True, null=True)),
                ('periods', models.ManyToManyField(blank=True, null=True, to='timescales.GeoPeriod')),
            ],
        ),
        migrations.CreateModel(
            name='GeoEon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('absolute_number', models.IntegerField(default=0)),
                ('eon_order_number', models.IntegerField(default=0)),
                ('summary', models.TextField()),
                ('life', models.TextField(blank=True, null=True)),
                ('eras', models.ManyToManyField(blank=True, null=True, to='timescales.GeoEra')),
            ],
        ),
    ]
