# Generated by Django 3.2.7 on 2022-02-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timescales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoeon',
            name='eras',
            field=models.ManyToManyField(blank=True, to='timescales.GeoEra'),
        ),
        migrations.AlterField(
            model_name='geoera',
            name='periods',
            field=models.ManyToManyField(blank=True, to='timescales.GeoPeriod'),
        ),
    ]
