# Generated by Django 3.2.7 on 2022-02-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timescales', '0002_auto_20220227_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geoeon',
            name='eon_order_number',
        ),
    ]
